#include "DEFS.h"
      SUBROUTINE CAL_MATERIAL
      
      USE MOD_GLOBAL
	USE ADVT
      
      IMPLICIT NONE
	INTEGER NCON2
	INTEGER I,J,K,N,II
c      REAL MATERF(N_CTRDP1,KB) !V2410
      NCON2 = 2
      VTP = 0

c      CALL ADVT_HSIMT(CONCENTRATION,VF) !V2410
      CALL ADVT_HSIMT_GPU(CONCENTRATION,VF) !V2410
c      CALL PROFT(NCON2,VF,WSSURF) !V2410
      CALL PROFT_GPU(NCON2,VF,WSSURF) !V2410
      !CALL BCOND_TWO(1) !c V2410
c!$OMP TARGET DEFAULTMAP(present: allocatable)
c!$OMP TEAMS DISTRIBUTE PARALLEL DO COLLAPSE(2)
      DO concurrent (N=1:NUMMAT,K=1:KBM1) local(II) !c V2410
          II=I_MAT(N)
              VF(II,K)=VF(II,K)+MDIS(N)*DTI*VQDIST_MAT(N,K)/
     *        (DJ(II)*D(II)*DZ(K))
      ENDDO
c!$OMP END TARGET
c      PRINT*,VF(II,1),VF(NIM1(II),1),VF(NIP1(II),1),
c     *VF(NJM1(II),1),VF(NJP1(II),1) 
c!$OMP TARGET DEFAULTMAP(present: allocatable)
c!$OMP TEAMS DISTRIBUTE PARALLEL DO COLLAPSE(2)
      DO concurrent (I=1:N_CTRD_AG,K=1:KB) !c V2410
      IF(FSM(I).GE.0.5) THEN
          CONCENTRATION(I,K) = VF(I,K) !V2410
      ENDIF
      ENDDO
c!$OMP END TARGET
      
      
c!$OMP TARGET DEFAULTMAP(present: allocatable)
c!$OMP TEAMS DISTRIBUTE PARALLEL DO COLLAPSE(2)
      DO concurrent (N=1:NUMEBC,K=1:KB) local(II) !c V2410
          II = NETA(N)
          CONCENTRATION(II,K) = VF(II,K) !V2410
      ENDDO
c!$OMP END TARGET
	RETURN  
	END SUBROUTINE CAL_MATERIAL
      