	SUBROUTINE INSIDE(XM,YN,XB,YB,NB,IND)
	DIMENSION XB(NB),YB(NB),YC(1000)
	NC=0
	 
	DO 50 K=1,NB
	    KP1=K+1-K*(K/NB)
	    KW=K
	    IF(XB(K)-XB(KP1)) 20, 50, 10
10	    KW=KP1
20	    KE=K+KP1-KW
	    IF(XM-XB(KE)) 30, 40, 50
30	    IF(XM.LE.XB(KW)) GO TO 50
40	    NC=NC+1
	    SLOPE=(YB(KE)-YB(KW))/(XB(KE)-XB(KW))
	    YC(NC)=YB(KW)+(XM-XB(KW))*SLOPE
50	CONTINUE
	IND=0
	IF(NC.GT.0)THEN
	    DO K=1,NC
	        IF(YC(K).LT.YN) IND=1-IND
	    ENDDO
      ENDIF
      
	RETURN
	END SUBROUTINE INSIDE
