      SUBROUTINE INTER_S_VERTICAL  !LTY 2012.12 FOR  PERDICTION
      USE MOD_GLOBAL 
      IMPLICIT NONE
      INTEGER,PARAMETER::IMNMC=337,JMNMC=225,KBM1NMC=10,KBNMC=11
      
	REAL OBX(50),OBY(50),OBS(50,KBM1NMC)
	REAL HNMC(400,400)
	REAL XNMC(400,400),YNMC(400,400)
	REAL DIS1NMC,SURFSN
	REAL DISNMC(N_CTRDP1)
	REAL RESNMC(50,KBM1NMC),ELFNMC(50),DIS2NMC(50),I1(50),J1(50)  !!QC_增加水位检查ELF，增加同化点距离检查DIS2NMC
      INTEGER INMC,JNMC,KKNMC,KOBNMC,NNMC,RELNMC
      REAL XXNMC,DIFFNMC
      
      OPEN(10,FILE='input/OBSERVEDDATA.DAT')
	OPEN(40,FILE='output/NMC/29MODEL_RESULT.DAT')
      OPEN(41,FILE='output/NMC/29MODEL_RESULT_DIFF.DAT')  !!QC_检查数据与计算值差异大于1的点
      WRITE(41,'(200A12)') 'INMC','EL','DIS','I','J','DIFF','OBS','S'
      DIS1NMC=999999.
      
	INMC=1
      IF(ABS(DELTA_TGTH_S1)<=5.*DTI)THEN
c	DO WHILE(.NOT.EOF(10))
	DO WHILE(1)
	    READ(10,*,end=100)OBX(INMC),OBY(INMC),XXNMC,OBS(INMC,1)
	    INMC=INMC+1
      END DO
100   continue
      ENDIF
      CLOSE(10)
	KOBNMC=INMC-1
      
	DO KKNMC=1,KOBNMC
      DIS1NMC=9999999.
      DO INMC=1,N_CTRD
      IF(H(INMC).GE.0 .AND. FSM(INMC).GE.0.)THEN 
          DISNMC(INMC)=SQRT((OBX(KKNMC)-XR(INMC))**2
     *    +(OBY(KKNMC)-YR(INMC))**2)
          DIS1NMC=MIN(DISNMC(INMC),DIS1NMC)
      ENDIF
      ENDDO
      DO INMC=1,N_CTRD
      IF(DISNMC(INMC).EQ.DIS1NMC
     *.AND. H(INMC).GE.0. .AND. ELF(INMC).NE.0.)THEN    
          DO NNMC=1,KBM1NMC
              RESNMC(KKNMC,NNMC)=S(INMC,NNMC)
          ENDDO
          ELFNMC(KKNMC)=ELF(INMC)  !!QC_水位检查
          DIS2NMC(KKNMC)=DIS1NMC   
          I1(KKNMC)=INMC
      ENDIF
      ENDDO
      ENDDO
      

!!!  QC_改为以下插值方法，防止出现同化后盐度过大的现象
      DO INMC=1,KOBNMC
	    DIFFNMC=OBS(INMC,1)-RESNMC(INMC,1)
          IF(RESNMC(INMC,1).LT.0.01)THEN
              RESNMC(INMC,1)=0.01
          ENDIF          
          SURFSN = OBS(INMC,1) / RESNMC(INMC,1)
          IF (SURFSN.GE.1.2) THEN
              SURFSN = 1.2
          ELSEIF (SURFSN.LE.0.8) THEN
              SURFSN = 0.8
          ENDIF         
	    DO NNMC=2,KBM1NMC
              OBS(INMC,NNMC) = RESNMC(INMC,NNMC)+DIFFNMC  !等差同化
              IF(OBS(INMC,NNMC).GT.34)THEN
                  OBS(INMC,NNMC)=34.
              ENDIF
	    ENDDO
      ENDDO
!!!  QC_END         
      DO INMC=1,KOBNMC
          WRITE(40,'(12G)')OBX(INMC),OBY(INMC),(OBS(INMC,NNMC),NNMC=1,
     *KBM1NMC)
          WRITE(41,'(17G)')INMC,ELFNMC(INMC),DIS2NMC(INMC),
     *I1(INMC),
     *ABS(RESNMC(INMC,1)-OBS(INMC,1)),
     *OBS(INMC,1),(RESNMC(INMC,NNMC),NNMC=1,KBM1NMC)    !!!QC_检查同化的盐度数据差异、站点水位、同化点距离
      ENDDO
      CLOSE(40)
      END SUBROUTINE INTER_S_VERTICAL
      