      MODULE MOD_HEAT
      SAVE
      CONTAINS
      
      SUBROUTINE SURFRAD_UNIFORM(FFF)   
      USE MOD_GLOBAL
      REAL FFF(N_CTRDP1,KB)
#ifdef HEATFLUX_BULK     
	REAL  AS_RAD, EP_RAD, L_RAD   
	REAL A_RAD,B_RAD,CE_RAD,RHOA_RAD, CP_RAD  
      REAL CH_RAD,E0_RAD,SPRO_RAD
	REAL EZ_RAD,E_RAD,K_RAD,QW_RAD,QZ_RAD,AIRTMP
      REAL DHR,SBC,REFL,WNDSH,ZU,ZT,ZQ,SPECHT,RLHE,RHAIR,BAROP,RELHUM
      REAL ANGLE,TOL,UW,WTOUT,WQOUT,CD,EA,ESS,T2K,FAC,RAN,RB
      REAL RHOAIR,EAS,ES,ESEADIFF,FW,RL1,RL2,RLWCO
      INTEGER IHR,I,J,NERR
      REAL*8 SHOUR,CHRS
      REAL ALAT,ALON,BAROPNT,SSIN,
     *UZ,RHBY100,CLDFRC,SWR,RLW,HNOT,WENOT
     *,WT, WQ , RLWC ,SWOBS

      DHR = 0.01      
      SBC = 2.0411E-7 
      REFL = 0.07
	SPRO_RAD=-4.186E6
	AS_RAD=0.07
	EP_RAD=5.67051E-8
	L_RAD=2.5E6
      A_RAD=7.45  
	B_RAD=235.0
	CE_RAD=1.2E-3    
	RHOA_RAD=1.292
	CP_RAD=1.005E3 
      CH_RAD=1.0E-3    
	E0_RAD=6.11E2
      IHR=0
      CALL DATEHR(IDAY0,IMONTH,IYEAR,IHR,0,SHOUR)
      CHRS = SHOUR + THOUR
      CALL GETDATE(IDC,IMC,IYC,IHC,IMINC,CHRS)
      WNDSH=1.
      ZU = 10.
      ZT = 10.
      ZQ = 10.
      SPECHT = 1004.  ! SPECIFIC HEAT (JOULES/KG/DEG C)
      RLHE = 2.47E3   ! LATENT HEAT OF EVAPORATION (JOULES/G)
      RHOAIR = (1.25E-03)     ! AIR DENSITY
      
	DO I=1,N_CTRD
	IF(FSMADD(I).EQ.1.)THEN
      ALAT=LAT(I)
      ALON=LON(I)
      BAROP=APR(I)/100.
      BAROPNT=APR(I)
      SSIN=FFF(I,1)
      UZ=SQRT(WINDU(I)**2+WINDV(I)**2)
      RELHUM=RHM(I)
      RHBY100=RHM(I)/100.
      CLDFRC=CLOUD(I)	      
      AIRTMP=ATP(I)
      UZ=AMAX1(UZ,0.1)  
      CALL HITFLX (ALAT,ALON,IYC,IMC,IDC,IHC,IMINC,BAROPNT,SSIN,
     +AIRTMP,UZ,ANGLE,RHBY100,CLDFRC,DHR,SWR,RLW,HNOT,WENOT)
      SWOBS = SWR
      CALL BULK(UZ,ZU,AIRTMP,ZT,RELHUM,ZQ,SSIN,TOL,UW,WTOUT,WQOUT,
     *CD,BAROP,NERR)
      CALL VAPOR(EA,ESS,RELHUM,SSIN,BAROP)   
      T2K = 273.2+AIRTMP
      FAC = 1.0+0.17*CLDFRC**2   !CLDFRC IS IN 0-1 SCALE
      RAN = 1000.0/3600.0*9.37E-6*SBC*T2K**6*FAC*(1.0-0.03)
      RB = 1000.0/3600.0*0.97*SBC*(SSIN+273.2)**4
      CALL VAPOR(EAS,ES,RELHUM,AIRTMP,BAROP)!  FOR AIR TEMPERATURE
      ESEADIFF = (ESS-EAS)/1.3333           ! FROM MB TO MMHG

      FW   = 6.9+0.345*UZ**2           ! WIND FUNCTION EDINGER ET AL. 1974
      WT   = -0.62*FW*(SSIN-AIRTMP)    ! SENSIBLE HEAT FLUX (W/M2)
      WQ   = -1.*FW*ESEADIFF           ! LATENT HEAT FLUX (W/M2)
      RLWC  = RAN - RB
      SWOBS=SWOBS*(1.0-REFL)

      WTSURF(I)=SWOBS+RLWC+WQ+WT
      WTSURF(I)=WTSURF(I)/SPRO_RAD*RAMP
      SWRAD(I)=SWOBS/SPRO_RAD*RAMP
	    
      ENDIF
      ENDDO
#elif defined HEATFLUX_SPECI  
!	REAL S_RAD, AS_RAD, EP_RAD, C_RAD, SETA_RAD, TZ_RAD, L_RAD 
!	REAL A_RAD, B_RAD, F_RAD, CE_RAD, UZ_RAD, RHOA_RAD, CP_RAD
!      REAL CH_RAD, E0_RAD, P_RAD, SPRO_RAD
!	REAL EZ_RAD, E_RAD, K_RAD, QW_RAD, QZ_RAD
!	SPRO_RAD = -4.186E6
!     	S_RAD = 1367.0
!	AS_RAD = 0.07
!	EP_RAD = 5.67051E-8
!	C_RAD = 0.67
!	SETA_RAD = 31.0
!C----------------------------------BYXSY-------------------------------
!	TZ_RAD = 30.5 !26.3 !LXY
!	L_RAD = 2.5E6
!      A_RAD = 7.45  
!	B_RAD = 235.0
!	F_RAD = 0.81
!	CE_RAD = 1.3E-3
!	UZ_RAD = 2.9
!	RHOA_RAD = 1.292
!	CP_RAD = 1.005E3 
!      CH_RAD = 1.3E-3
!	E0_RAD = 6.11E2
!	P_RAD = 1.0059E5
!      
C     S_RAD  太阳常数(单位时间射达大气上界的单位面积上的太阳辐射总能量);    K_RAD  云的阻拦系数； 
C     AS_RAD 反射率(从海面反射的辐射与入射到海面的总辐射之比);
C     C_RAD  云量;                EP_RAD   STEFAN-BOLTZMAN常数;     SETA_RAD    地理纬度;    
C     TZ_RAD 参考高度气温;        F_RAD    相对湿度;                A_RAD,B_RAD 常数(水面和冰面的不同）;
C     L_RAD  水的比蒸发潜热；     RHOA_RAD 空气密度;                UZ_RAD      参考高度风速；  
C     CE_RAD 水汽输送系数;        CP_RAD   空气的比定压热容;        CH_RAD      块体交换系数；
C     EZ_RAD 参考高度空气水汽压;  E_RAD    水面饱和水汽压;          P_RAD       空气压强;
C     QW_RAD 海面饱和比湿;		QZ_RAD   参考高度比湿
	
!      K_RAD = 0.59+0.005*(SETA_RAD-20.0)
!	E_RAD = E0_RAD*(10.**(A_RAD*TZ_RAD/(B_RAD+TZ_RAD)))
!	EZ_RAD = F_RAD*E_RAD
!	QW_RAD = 0.622*E_RAD/P_RAD
!	QZ_RAD = 0.622*EZ_RAD/P_RAD
!      FFF = FFF+TZ_RAD !LXY
!      DO I = 1,N_CTRD_AG
!      IF(FSM(I).GT.0.0) THEN
!C------------------------通过海面进入海洋的短波辐射能---------------------
!	    QS_RAD(I) = S_RAD/2.0*(1.0-0.7*C_RAD)*(1.0-AS_RAD)
!	    QS_RAD(I) = QS_RAD(I)*0.50  
!C------------------------有效回辐射-------------------------------------
!	    QB_RAD(I) = (0.94*EP_RAD*((TZ_RAD+273.0)**4)*  
!     *    (0.39-0.005*SQRT(EZ_RAD))*(1-K_RAD*C_RAD*C_RAD)+
!     *    3.76*EP_RAD*((TZ_RAD+273.0)**3)*(FFF(I,1)-TZ_RAD)) 
!C------------------------海水蒸发消耗的热能（潜热）-----------------------
!	    QE_RAD(I) = (L_RAD*RHOA_RAD*CE_RAD*UZ_RAD*(QW_RAD-QZ_RAD))
!C------------------------海气之间的显热交换的热能（感热）-----------------
!          QH_RAD(I) = (CP_RAD*RHOA_RAD*CH_RAD*UZ_RAD*(FFF(I,1)-TZ_RAD))
!          QH_RAD(I) = QH_RAD(I)*4.8
!C------------------------海洋吸收的净热能--------------------------------
!	    WTSURF(I) = QS_RAD(I)-QB_RAD(I)-QE_RAD(I)-QH_RAD(I)
!C----------------------------------------------------------------------
!          WTSURF(I) = WTSURF(I)/SPRO_RAD
!	    SWRAD(I) = QS_RAD(I)/SPRO_RAD
!      ENDIF
!      ENDDO
!      FF = FF-TZ_RAD !LXY
#endif
	RETURN
      END SUBROUTINE SURFRAD_UNIFORM
      
      
      
#ifdef HEATFLUX_BULK          
      SUBROUTINE BULK(UZ,ZU,TZ,ZT,RH,ZQ,TSFC,TOL,UW,WT,WQ,CD,BP,NERR)
        IMPLICIT NONE
		REAL WIR,CDA,CTS,CTU,CEA,UCH,RHOEFLT,VONK,UZ,ZU,TZ,ZT
		REAL RH,ZQ,TSFC,TOL,UW,WT,WQ,CD,BP,DELTH,QZ,SALT,DELQ
		REAL TKELV,F1,T0,UDT,RHDEFLT,F2,U3,ZUOL,ZTOL,ZQOL
		REAL TTOL,P10,PG10,S10,SG10,PHIM,PHI,PSIM,PSI,PHIT,PSIMT
		REAL PSIT,PHIQ,PSIMQ,PSIQ,RK,ITER,UP,CP,U10,SQRT,DIFF,CDN
		REAL WTR,SQCD,RCD,CTN,RCDT,CT,RKT,DTH10,CEN,RCDQ,CE,A
		REAL U,DTH
		INTEGER NERR
      LOGICAL BIG
      WTR(A,U,DTH)=0.002+A*U*DTH
CMNT
CMNT
        CDA = 0.00115
        CTS = 0.00075
        CTU = 0.00115
        CEA = 0.00115
        UCH = 10.
        RHDEFLT = 75.
        VONK = 0.40

C

C	ADDED MPS - SEE ABOVE NOTE.  RETURN ERROR VALUE FOR SUBROUTINE
      NERR = 0
CMNT                         ARE TEMPS RELIABLE??
      IF (ZT .GT. 0.2) GO TO 1
      TOL=0.0
      GO TO 3
CMNT  YES, CALCULATE A BULK STABILITY PARAMETER AT 10 METERS FROM
CMNT    DELTH,SURFACE - AIR POTENTIAL TEMPERATURE DIFFERENCE
CMNT    QSFC, SURFACE ABSOLUTE HUMIDITY
CMNT    TO, LOCAL MEAN VIRTUAL TEMERATURE
1     DELTH=TSFC-TZ-0.01*ZT
CMNT  THIS IS THE SEA MINUS AIR POT. TEMP. DIFF
      IF (ZQ .LE. 0.0) RH=RHDEFLT
      QZ=RH*QSAT0(TZ,BP)*.01

C	CORRECT FOR SALT WATER AT 35PPT
      SALT = 0.9815
      DELQ=SALT*QSAT0(TSFC,BP)-QZ
      TKELV=273.16 + TZ
      F1=0.00000172
      T0=TKELV+QZ*F1*TKELV**2
CMNT  
CMNT  IS /WT/ LARGE ENOUGH TO USE TRANSFER COEFFICIENTS?
      UDT=UZ*DELTH
      IF ((UDT .LT. 10.) .AND. (UDT. GT. -15.)) GO TO 2
CMNT  YES
      BIG=.TRUE.
      F2=1.00
      IF (DELTH .LT. 0.0) F2=0.70
      TOL=0.0-1000.*F2/T0/UZ**2*(DELTH+F1/F2*DELQ*T0**2)
      GO TO 3
CMNT  
CMNT  NO,     DEAL WITH SMALL SENSIBLE HEAT FLUXES
2     BIG=.FALSE.
      A=0.0010
      IF (DELTH .LT. 0.0) A=0.0008
      WT=WTR(A,UZ,DELTH)
      WQ=CEA*UZ*DELQ
      U3=(SQRT(CDA)*UZ)**3
      TOL=0.0-39./U3/T0*(WT+F1*WQ*T0**2)
CMNT
CMNT     RETURN WITH ONLY TOL IF ZU NOT GREATER THAN 0.2
3     IF (ZU .LE. 0.2) RETURN
      ZUOL=TOL*ZU/10.0
      ZTOL=TOL*ZT/10.0
      ZQOL=TOL*ZQ/10.0
CMNT     EVALUATE THE STABILITY FUNCTIONS IN FZOL
      TTOL = TOL
      CALL FZOL(TTOL,P10,PG10,S10,SG10)
      TOL = TTOL
      CALL FZOL(ZUOL,PHIM,PHI,PSIM,PSI)
      CALL FZOL(ZTOL,PHI,PHIT,PSIMT,PSIT)
      CALL FZOL(ZQOL,PHI,PHIQ,PSIMQ,PSIQ)
CMNT
CMNT     SOLVE FOR U10 AND CDN ITERATIVELY
      RK=(ALOG(ZU/10.0)-PSIM+S10)/VONK
      ITER=1
      UP=UZ/(1.0+SQRT(CDA)*RK)
22    CP=CDA
      IF (UP .GT. UCH) CP=(0.49+0.065*UP)/1000.
      U10=UZ/(1.0+SQRT(CP)*RK)
      DIFF=(UP-U10)/UP
      UP=U10
      IF (DIFF .LE. 0.01) GO TO 4
      ITER=ITER+1
      IF (ITER .LE. 5) GO TO 22
C**********************************************************
C	COMMENTED OUT FOLLOWING 5 LINES, ADDED RETURN 
C	MPS - SEE EXPLANATION AT BEGINNING OF PROGRAM
C      WRITE(6,66)ITER,U10,DIFF,CP
C 66    FORMAT('-',5X,'TOO BAD, FAILED TO CONVERGE IN 5 ITERATIONS',I6,
C     13F16.4)
C      STOP
	NERR = ITER
	RETURN
C**********************************************************
CMNT
CMNT      SOLVED FOR U10, NOW FIND CDN AND CD
CMNT      THEN GET UW FROM BULK FORMULA
4     CDN=CDA
      IF (U10 .GT. UCH) CDN=(0.49+0.065*U10)/1000.
      SQCD=SQRT(CDN)
      RCD=1.0+SQCD/VONK*(ALOG(ZU/10.0)-PSIM)
      CD=CDN/RCD**2
      UW=0.0-CD*UZ**2
CMNT
CMNT  SENSIBLE HEAT FLUX IF ZT GREATER THAN 0.02
      IF (ZT .LE. 0.02) GO TO 5
      CTN=CTU
      IF (DELTH .LT. 0.0) CTN=CTS
      RCDT=1.0+SQCD/VONK*(ALOG(ZT/10.0)-PSIMT)
      CT=CTN/RCDT/(1.0+CTN/VONK/SQCD*(ALOG(ZT/10.)-PSIT))
      WT=CT*UZ*DELTH
      IF (BIG) GO TO 5
CMNT       CALCULATE SMALL SENSIBLE HEAT FLUX
      RKT=(ALOG(ZT/10.0)-PSIT+SG10)/VONK
      DTH10=DELTH-CT/SQRT(CD)*RKT*(DELTH)
      WT=WTR(A,U10,DTH10)
CMNT
CMNT      LATENT HEAT (MOISTURE) FLUX IF ZQ SET > 0.02
5     IF (ZQ .GT. 0.02) GO TO 6
CMNT  MOD. ORIGINAL RETURNED IF ZQ .LE. 0.02 WITHOUT
CMNT  CALCULATING A NEW WQ
      WQ=CEA*UZ*DELQ
      RETURN
6     CEN=CEA
      RCDQ=1.0+SQCD/VONK*(ALOG(ZQ/10.0)-PSIMQ)
      CE=CEN/RCDQ/(1.0+CEN/VONK/SQCD*(ALOG(ZQ/10.)-PSIQ))
      WQ=CE*UZ*DELQ
      RETURN
      END SUBROUTINE BULK
      
      
      SUBROUTINE DATEHR(IDAY,IMON,IYR,IHR,IMIN,THOURS)
C
C*************************************************************************
C     ECOMSED MODEL
C     VERSION 1.3
C     FEBRUARY 2002
C*************************************************************************
*               COPYRIGHT (C) 2002, HYDROQUAL, INC.                      *
*                                                                        *
*  THESE CODED INSTRUCTIONS, STATEMENTS, AND COMPUTER PROGRAMS  CONTAIN  *
*  UNPUBLISHED  PROPRIETARY  INFORMATION OF HYDROQUAL, INC., AND         *
*  ARE PROTECTED BY FEDERAL COPYRIGHT LAW.  THEY  MAY  NOT BE DISCLOSED  *
*  TO  THIRD  PARTIES  OR COPIED OR DUPLICATED IN ANY FORM, IN WHOLE OR  *
*  IN PART, WITHOUT THE PRIOR WRITTEN CONSENT OF HYDROQUAL, INC.         *
*                                                                        *
* POINT OF CONTACT: ECOMSED-SUPPORT@HYDROQUAL.COM                        *
C*************************************************************************
C     THIS ROUTINES GIVES THE HOUR (THOURS) CORRESPONDING TO DAY, MON,
C     YEAR, HOUR AND MINUTES
C
C  OSSM01.FOR
C
      IMPLICIT NONE
	  INTEGER I,IDAY,IMON,IYR,IHR,IMIN,IYRS,J,IJ,K,IDAYS
	  INTEGER LPRT,LCON,LTPE,LDSK,LWCON
	  
	  
	  
      COMMON /DEVCES/ LPRT,LCON,LTPE,LDSK,LWCON
      INTEGER MON(12,2)
      INTEGER LYEAR(4)
            REAL*8 THOURS
       LYEAR(1) = 8784
       LYEAR(2) = 8760
       LYEAR(3) = 8760
       LYEAR(4) = 8760

       MON(1,1) = 0
        MON(2,1) = 31
        MON(3,1) = 59
        MON(4,1) = 90
        MON(5,1) = 120
        MON(6,1) = 151
        MON(7,1) = 181
        MON(8,1) = 212
        MON(9,1) = 243
        MON(10,1) = 273
        MON(11,1) = 304
        MON(12,1) = 334

        MON(1,2) = 0
        MON(2,2) = 31
        MON(3,2) = 60
        MON(4,2) = 91
        MON(5,2) = 121
        MON(6,2) = 152
        MON(7,2) = 182
        MON(8,2) = 213
        MON(9,2) = 244
        MON(10,2) = 274
        MON(11,2) = 305
        MON(12,2) = 335



      THOURS=0.0
      IF((IMON.LT.1).OR.(IMON.GT.12)) GOTO 800
      IF((IDAY.LT.1).OR.(IDAY.GT.31)) GOTO 800
C CHANGE YEAR FROM 2 DIGITIS TO 4 DIGITS 
      IYRS=IYR-1900
      IF(IYRS.EQ.0) GOTO 12
      DO 10 J=1,IYRS
      IJ=MOD(J,4)
      IF(IJ.EQ.0) IJ=4
      THOURS=THOURS+FLOAT(LYEAR(IJ))
 10   CONTINUE
      K=1
 11   IF(IJ.EQ.4) K=2
      IDAYS=MON(IMON,K)+IDAY-1
      THOURS=THOURS+FLOAT(24*IDAYS)+FLOAT(IHR)+FLOAT(IMIN)/60.
      GOTO 999
 12   IJ=4
      GOTO 11
 800  WRITE(*,101) IDAY,IMON,IYR,IHR,IMIN
 101  FORMAT(10X,'ERROR IN DATE FIELD',I2,'/',I2,'/',I2,1X,I2,':',I2)
 999  RETURN
      END SUBROUTINE DATEHR
      
      
      SUBROUTINE FZOL(ZOL,PHIM,PHIG,PSIM,PSIG)
		  IMPLICIT NONE
		  REAL X,PHIM,PHIG,PSIG,PSIM,ZOL
C FZOL:    SUBROUTINE TO ESTIMATE THE STABILITY FUNCTIONS
CMNT       USING THE MOST UP TO DATE FLUX-PROFILE RELATIONSHIPS
CMNT
      IF (ZOL .GE. 0.0) GO TO 2
CMNT             UNSTABLE
      X=(1.0-16.0*ZOL)**0.25
      PHIM=1.0/X
      PHIG=PHIM**2
      PSIG=2.0*ALOG(0.5+0.5*X**2)
      PSIM=0.5*PSIG+2.0*ALOG(0.5*(1.0+X))-2.0*ATAN(X)+1.571
      RETURN
CMNT
CMNT     STABLE
2     PHIG=1.0+7.0*ZOL
      PHIM=1.0+7.0*ZOL
      PSIG=-7.0*ZOL
      PSIM=-7.0*ZOL
      RETURN
      END SUBROUTINE FZOL
      
               
      SUBROUTINE GETDATE(ID,IM,IY,IH,IMIN,THOURS)
C
C*************************************************************************
C     ECOMSED MODEL
C     VERSION 1.3
C     FEBRUARY 2002
C*************************************************************************
*               COPYRIGHT (C) 2002, HYDROQUAL, INC.                      *
*                                                                        *
*  THESE CODED INSTRUCTIONS, STATEMENTS, AND COMPUTER PROGRAMS  CONTAIN  *
*  UNPUBLISHED  PROPRIETARY  INFORMATION OF HYDROQUAL, INC., AND         *
*  ARE PROTECTED BY FEDERAL COPYRIGHT LAW.  THEY  MAY  NOT BE DISCLOSED  *
*  TO  THIRD  PARTIES  OR COPIED OR DUPLICATED IN ANY FORM, IN WHOLE OR  *
*  IN PART, WITHOUT THE PRIOR WRITTEN CONSENT OF HYDROQUAL, INC.         *
*                                                                        *
* POINT OF CONTACT: ECOMSED-SUPPORT@HYDROQUAP.COM                        *
C*************************************************************************
C     THIS ROUTINE GIVES THE DAY, MON, YEAR, HOUR AND MINUTES 
C     CORRESPONDING TO THE GIVEN HOURS
C
C  OSSM01.FOR
C
       IMPLICIT NONE
	   INTEGER I,LAYER,MON,ID,IM,IY,IH,IMIN,IHOURS,JFLAG,LPRT
	   INTEGER LCON,LTPE,LDSK,LWCON,K,IDAYS,LYEAR
	   REAL XHOURS,YDSUM
      COMMON /DEVCES/ LPRT,LCON,LTPE,LDSK,LWCON
      DIMENSION MON(12,2)
      DIMENSION LYEAR(4)
      REAL*8 THOURS

        LYEAR(1) = 8784
        LYEAR(2) = 8760
        LYEAR(3) = 8760
        LYEAR(4) = 8760

        MON(1,1) = 0
        MON(2,1) = 31
        MON(3,1) = 59
        MON(4,1) = 90
        MON(5,1) = 120
        MON(6,1) = 151
        MON(7,1) = 181
        MON(8,1) = 212
        MON(9,1) = 243
        MON(10,1) = 273
        MON(11,1) = 304
        MON(12,1) = 334

        MON(1,2) = 0
        MON(2,2) = 31
        MON(3,2) = 60
        MON(4,2) = 91
        MON(5,2) = 121
        MON(6,2) = 152
        MON(7,2) = 182
        MON(8,2) = 213
        MON(9,2) = 244
        MON(10,2) = 274
        MON(11,2) = 305
        MON(12,2) = 335

        THOURS=THOURS+.00417   !LINJUN,单精度的数位有限？
      XHOURS=REAL(MOD(INT(THOURS+0.1),24))  !HUI WU
      IH=INT(XHOURS+0.1)                     !HUI WU   为了避免取整的错误
      IMIN=INT((XHOURS-FLOAT(IH))*60.)

      IHOURS=INT(THOURS-XHOURS+.001)
      IY=0
      YDSUM=0
 5    CONTINUE
      DO 10 I=1,4
      YDSUM=YDSUM+LYEAR(I)
      IY=IY+1
      IF(YDSUM.GT.IHOURS) GOTO 75
      IF(YDSUM.EQ.IHOURS) GOTO 85
 10   CONTINUE
      GOTO 5
 75   YDSUM=YDSUM-LYEAR(I)
      IY=IY-1
  85   IF(I.EQ.1) GOTO 200
      GOTO 100
 100  CONTINUE
      K=1
 110  IDAYS=(IHOURS-YDSUM)/24+1
      DO 120 JFLAG=1,12
      IF(MON(JFLAG,K).GE.IDAYS) GOTO 130
 120  CONTINUE
      IM=12
      ID=IDAYS-MON(12,K)
      GOTO 999
 130  ID=IDAYS-MON(JFLAG-1,K)
      IM=JFLAG-1
      GOTO 999
 200  K=2
      GOTO 110
 999  CONTINUE
      THOURS=THOURS-.00417
C CHANGE YEAR FROM 2 DIGITIS TO 4 DIGITS
      IY=IY+1900
      RETURN
      END SUBROUTINE GETDATE
      
      SUBROUTINE IJDAY(D,M,Y,J)
C     ************************************************************
C**   WHERE...
C        D.... DAY (1-31) COMPONENT OF GREGORIAN DATE
C        M.... MONTH (1-12) COMPONENT
C        Y.... YEAR (E.G., 1979) COMPONENT
C        J.... CORRESPONDING JULIAN DAY NUMBER
C     ************************************************************
       IMPLICIT NONE
      INTEGER*4 C, J, MO, YR
C     INTEGER*2 D,M,Y
      INTEGER*4 D, M, Y
C
      YR = Y
      IF (M.GT.2) THEN
        MO = M - 3
      ELSE
        MO = M + 9
        YR = YR - 1
      END IF
C
      C = YR / 100
      YR = YR - C * 100
      J = (146097*C) / 4 + (1461*YR) / 4 + (153*MO+2) / 5 + D + 1721119
C
C     CONVERT TO DAYS SINCE MAY 23, 1968 
C       (WHICH IN TRUE JULIAN DAY IS 2440000)
      J = J - 2440000
      RETURN
      END SUBROUTINE IJDAY
      
        SUBROUTINE HITFLX (ALATJ,XLNG0,IYR,IMON,IDAY,IHR,IMT,PSS,TSS,
     + DRYBT,VMOD,ANGLE,RH,CLOUD,DHR,SWR,RLW,HNOT,WENOT)
C
C        SUBROUTINE HITFLX (ALATJ,XLNG0,GMT,IYR,IMON,IDAY,IHR,PSS,TSS,
C     + DRYBT,VMOD,ANGLE,RH,CLOUD,DHR,SWR,RLW,HNOT,WENOT,HFS,DHFS,
C     +XKS,TEMPE,HEATXL,ESATS,ESATA,FWW,DIFEA)
C 
C    THIS SUBROUTINE CALCULATES SOLAR (SHORT WAVE) RADIATION,
C    REFLECTED (LONG WAVE) RADIATION, SENSIBLE HEAT FLUX,
C    LATENT HEAT FLUX, TOTAL HEAT FLUX AND PARTIAL DERIVATIVE,
C    D (HEAT FLUX) /DT, USED FOR LINEAR CORRECTION OF THE TOTAL
C    HEAT FLUX BASED ON SOME VALUE OF THE SEA SURFACE TEMPERATURE
C    DIFFERENT FROM THE GIVEN VALUE.  ALL UNITS ARE IN SI.
C
C    INPUT DATA:
C 
C    ALATJ =       LATITUDE, IN DEGREES
C    XLNG0 =       LONGITUDE, IN DEGREES WEST
C    GMT   =       SHIFT IN THE LOCAL TIME VERSUS GMT
C                  (FOR INSTANCE, FOR DELAWARE BAY LOCATION GMT=5.0)
C CHANGE IYR TO 4-DIGIT NUMBER 
C    IYR   =       YEAR (ONLY TWO LAST DIGITS, SUCH AS 84 FOR 1984)
C END CHANGE 
C    IMON  =       MONTH (1 FOR JANUARY, 2 FOR FEBRUARY ETC.)
C    IDAY  =       JULIAN DAY
C    IHR   =       HOUR (0 FOR MIDNIGHT, 12 FOR MIDDAY, ETC.)
C    PSS   =       ATMOSPHERIC PRESSURE AT THE SEA SURFACE LEVEL
C                  (NEWTON/M**2; 1000 MB WILL BE EQUAL TO 1.0E5)
C    TSS   =       SEA SURFACE TEMPERATURE (DEG. C)
C    DRYBT =       DRY BULB TEMPERATURE (DEG. C)
C    VMOD  =       AMPLITUDE OF THE WIND VELOCITY (M/SEC)
C    ANGLE =       WIND DIRECTION (ANGLE) (IN DEGREES)
C    RH    =       RELATIVE HUMIDITY (BETWEEN 0.0 AND 1.0)
C    CLOUD =       CLOUDINESS  (BETWEEN 0.0 AND 1.0)
C    DHR   =       PERIOD OF AVERAGING FOR SOLAR RADIATION (HOURS)
C    XKS   =	   TRANSFER COEFFICIENT
C    TEMPE =       EQUIVALENT TEMPERATURE
C    HEATXL=       LINEARIZED HEAT FLUX COMPUTED FROM TRANFER 
C                  COEFFICIENT, EQUIVALENT TEMPERATURE AND ATMOSPHEREIC
C                  TEMPERATURE. HEATXL=-XKS*(TEMPE-DRYBTP)
C
C    OUTPUT DATA:
C
C    SWR =       SHORT WAVE RADIATION INCLUDING CLOUDINESS (WATT/M**2)
C    RLW   =       REFLECTED LONG WAVE RADIATION (WATT/M**2)
C    HNOT  =       SENSIBLE HEAT FLUX (WATT/M**2)
C    WENOT =       LATENT HEAT FLUX (WATT/M**2)
C    HFS   =       TOTAL HEAT FLUX  (WATT/M**2)
C    DHFS  =       D (HEAT FLUX) / DT
C
C
       IMPLICIT NONE
       
       REAL,PARAMETER :: ALB1(20)=(/ .719, .656, .603, .480, .385,
     *   .300, .250, .193, .164, .131,
     *   .103, .084, .071, .061, .054,
     *   .039, .036, .032, .031, .030/)
       REAL,PARAMETER :: ZA(20)=(/ 90., 88., 86., 84., 82.,
     *   80., 78., 76., 74., 70.,
     *   66., 62., 58., 54., 50.,
     *   40., 30., 20., 10., 0.0 /)
       REAL,PARAMETER :: DZA(19)=(/ 2., 24., 50., 2., 2.,
     *   2., 2., 2., 4., 4.,
     *   4., 4., 4., 4., 10.,
     *   10., 10., 10., 10. /)
       REAL,PARAMETER ::  P62 = .62
       REAL,PARAMETER ::  P19 = .0019
       REAL,PARAMETER ::  P39 =  .39
       REAL,PARAMETER ::  P05 =.05
       REAL,PARAMETER ::  P6 = 0.6
       REAL,PARAMETER ::  P006 = 0.006
       REAL,PARAMETER ::  CH = 0.0015
       REAL,PARAMETER ::  CE = 0.0015
       
       REAL,PARAMETER ::  GMT=8.0  !20201125 WYH   !!!!!!!!!!!!!!!!!!!!!SPECIFY THE GMT IN THE ECS DOMAIN. GLOBAL ATTENTION!!!
       INTEGER, PARAMETER :: AMON(12)=(/0, 31, 60, 91, 121, 152,
     * 182, 213, 244, 274, 305, 355/)
      INTEGER, PARAMETER ::PAI=ACOS(-1.0)
      INTEGER, PARAMETER ::C5D9=5.0/9.0
      INTEGER, PARAMETER ::RADIAN=180.0/PAI
      INTEGER, PARAMETER ::ALATJZ=ALATJ/RADIAN
      INTEGER, PARAMETER ::TREF=273.16
      INTEGER, PARAMETER ::RTREF=1.0/TREF
      INTEGER, PARAMETER ::CP=1005.0
      INTEGER, PARAMETER ::RD=2.8708E2
      INTEGER, PARAMETER ::RV=4.6157E2
      INTEGER, PARAMETER ::W=2.4957E6
      INTEGER, PARAMETER ::WCP=W/CP
      INTEGER, PARAMETER ::WRV=W/RV
      INTEGER, PARAMETER ::POW=RD/CP
      INTEGER, PARAMETER ::DW=1.0
      INTEGER, PARAMETER ::SC=1353.0
      INTEGER, PARAMETER ::SIGSB=5.67E-8
      INTEGER, PARAMETER ::EMISS=.97
      INTEGER, PARAMETER ::CPCH = CP*CH
      INTEGER, PARAMETER ::CEDW = CE*DW
C
      INTEGER, PARAMETER ::TSSP=TSS
      INTEGER, PARAMETER ::DRYBTP=DRYBT
      INTEGER, PARAMETER ::TSS=TSS+273.16
      INTEGER, PARAMETER ::DRYBT=DRYBT+273.16
       
	   REAL P62,P19,P39,P05,P8,P6,P006,CH,CE,ALATJ,XLNG0,PSS,TSS,DRYBT
	   REAL VMOD,ANGLE,RH,CLOUD,DHR,SWR,RLW,HNOT,WENOT,REM
	   REAL GMT,PAI,C509,RADIAN,ALATJZ,TREF,RTREF,CP,RD,RV,W
	   REAL WCP,WRV,POW,DW,SC,SIGSB,EMISS,CPCH,CEDW,TSSP,DRYBTP
	   REAL CSD9,FJD,R,DLT,ALP,SLAG,HANG,TAUDA,COSZEN,SOLALT,COSZERS
	   REAL FRAC,RR2,SWDTOP,SWD,FXA,TRANS,TSEC,SWDSUR,ABSOR,ZEN,ACOS
	   REAL DZEN,ALBEDO,ESTS,C5D9,COSZRS,ESATS,QSAT,ESTA,ESATA,QASAT,QKM
	   REAL W1,W2,W3,W4,VTEMP,RHOAIR,RHOA,ENOT,FWW,DIFEA,AR,HSF,HNOT1
	   REAL ENOT1,RLW1,HFS1,DHFS,DELTA,XKS1,XKS2,XKS3,XKS
	   REAL HFS,W5,W6,W7,TEMPE,HEATXL
	   
	   INTEGER IYR,IMON,IDAY,IHR,K,JD,IDYR,ILEAP,NDAY,IMT,I,JAB

      INTEGER, PARAMETER :: KB=11
	  INTEGER, PARAMETER :: KBM1=KB-1
	  INTEGER, PARAMETER :: JMT=1
      REAL ATTEN(KB),ATTENZ(KB),ATTZ(KB)
	  INTEGER MON(12)
c      REAL ALB1(20),ZA(20),DZA(19),AMON(12)
c      REAL AMON(12)

c        ALB1(1) = .719
c        ALB1(2) = .656
c        ALB1(3) = .603
c        ALB1(4) = .480
c        ALB1(5) = .385
c        ALB1(6) = .300
c        ALB1(7) = .250
c        ALB1(8) = .193
c        ALB1(9) = .164
c        ALB1(10) = .131
c        ALB1(11) = .103
c        ALB1(12) = .084
c        ALB1(13) = .071
c        ALB1(14) = .061
c        ALB1(15) = .054
c        ALB1(16) = .039
c        ALB1(17) = .036
c        ALB1(18) = .032
c        ALB1(19) = .031
c        ALB1(20) = .030

c        ZA(1) = 90.
c        ZA(2) = 88.
c        ZA(3) = 86.
c        ZA(4) = 84.
c        ZA(5) = 82.
c        ZA(6) = 80.
c        ZA(7) = 78.
c        ZA(8) = 76.
c        ZA(9) = 74.
c        ZA(10) = 70.
c        ZA(11) = 66.
c        ZA(12) = 62.
c        ZA(13) = 58.
c        ZA(14) = 54.
c        ZA(15) = 50.
c        ZA(16) = 40.
c        ZA(17) = 30.
c        ZA(18) = 20.
c        ZA(19) = 10.
c        ZA(20) = 0.0

c        DZA(1) = 2.
c        DZA(2) = 2.
c        DZA(3) = 2.
c        DZA(4) = 2.
c        DZA(5) = 2.
c        DZA(6) = 2.
c        DZA(7) = 2.
c        DZA(8) = 2.
c        DZA(9) = 4.
c        DZA(10) = 4.
c        DZA(11) = 4.
c        DZA(12) = 4.
c        DZA(13) = 4.
c        DZA(14) = 4.
c        DZA(15) = 10.
c        DZA(16) = 10.
c        DZA(17) = 10.
c        DZA(18) = 10.
c        DZA(19) = 10.

c        DZA(2) = 24.
c        DZA(3) = 50.

c        P62 = .62
c        P19 = .0019
c        P39 =  .39
c        P05 =.05
c        P8  = .8


c        P6 = 0.6
c        P006 = 0.006

c        CH = 0.0015
c        CE = 0.0015

c        AMON(1) = 0
c        AMON(2) = 31
c        AMON(3) = 60
c        AMON(4) = 91
c        AMON(5) = 121
c        AMON(6) = 152
c        AMON(7) = 182
c        AMON(8) = 213
c        AMON(9) = 244
c        AMON(10) = 274
c        AMON(11) = 305
c        AMON(12) = 355

        MON=AMON
c        MON(1) = 0
c        MON(2) = 31
c        MON(3) = 60
c        MON(4) = 91
c        MON(5) = 121
c        MON(6) = 152
c        MON(7) = 182
c        MON(8) = 213
c        MON(9) = 244
c        MON(10) = 274
c        MON(11) = 305
c        MON(12) = 355

C
C  CALCULATE GMT BASED ON XLNG0 !THE METHODS CALCILATING THE GMT WOULD INDUCE THE "SWR" OBTAINED EAST OF 127.5 DELAYING ONE HOUR, WHICH HAD MADE "SWR" RESULTS NON-CONSECTIVE BESIDE THE TWO SIDE OF 127.5 E.
C      REM=AMOD(ABS(XLNG0),15.0)
C      GMT=INT(ABS(XLNG0)/15.0)
C      IF(REM.GT.7.5)GMT=GMT+1.0
C      IF(XLNG0.LT.0.)GMT=-1.*GMT
!      GMT=8.0  !20201125 WYH   !!!!!!!!!!!!!!!!!!!!!SPECIFY THE GMT IN THE ECS DOMAIN. GLOBAL ATTENTION!!!
C     SET UP MON ARRAY BASED ON WHETHER OR NOT THE CURRENT YEAR
C     IS A LEAP YEAR
C
      IF ( MOD(IYR,4) .NE. 0 ) THEN
      DO 5 I=3,12
      MON(I)=AMON(I)-1
    5 CONTINUE
      END IF
C
!      PAI=ACOS(-1.0)
!      C5D9=5.0/9.0
!      RADIAN=180.0/PAI
!      ALATJZ=ALATJ/RADIAN
!      TREF=273.16
!      RTREF=1.0/TREF
!      CP=1005.0
!      RD=2.8708E2
!      RV=4.6157E2
!      W=2.4957E6
!      WCP=W/CP
!      WRV=W/RV
!      POW=RD/CP
!      DW=1.0
!      SC=1353.0
!      SIGSB=5.67E-8
!      EMISS=.97
!      CPCH = CP*CH
!      CEDW = CE*DW
C
!      TSSP=TSS
!      DRYBTP=DRYBT
!      TSS=TSS+273.16
!      DRYBT=DRYBT+273.16
C****
C**** DOWNWARD IRRADIANCE AFTER PAULSON AND SIMPSON (JPO 1977)
C****        (SEE ALSO SIMPSON AND DICKEY - JPO 1981)
C****
C**** TYPE I
C     GAM1=-(1.0/150.0)
C     GAM2=-(1.0/2000.0)
C     R1=0.62
C**** TYPE III
C     GAM1=-(1.0/140.0)
C     GAM2=-(1.0/790.0)
C     R1=0.78
C     R11=1.0-R1
      DO 10 K=1,KB
      ATTEN(K)=0.0
      ATTENZ(K)=0.0
   10 CONTINUE
C     ATTEN(*)=R1*EXP(Z(*)*GAM1)+R11*EXP(Z(*)*GAM2)
C**** TAKE Z DERIVATIVE TO CALC THE DIVERGENCE OF DOWNWARD IRRADIANCE
C**** MULT BY IRRADIANCE AT SURFACE
C     ATTENZ(1)=(1.0-ATTEN(1))/DZ(1)
C     DO 1488 K=2,KB
C       ATTENZ(K)=(ATTEN(K-1)-ATTEN(K))/DZ(K)
C1488 CONTINUE
C     PRINT 1489,ATTENZ
C1489 FORMAT(2X,'ATTENUATION',(1X,10E12.4))
C****
C****
C**** SOLAR CALCULATES THE COS OF THE SUN'S ZENITH ANGLE,
C**** THE EARTH'S RADIUS VECTOR,AND SOLAR ALTITUDE FOR
C**** EACH LATITUDE.
C****
C**** R      = EARTH'S RADIUS VECTOR
C**** TAUDA  = TOTAL DAYLIGHT FRACTION
C**** COSZEN = COSINE OF ZENITH ANGLE
C**** SOLALT = SOLAR ALTITUDE
C****
      JD = MON(IMON) + IDAY
C
C   JD IS DESIGNED TO START AT JAN 1, 1984 00:00 AM
C
      JD  = JD + 2415020 + 25566 + 5115
C
C   THIS IF-THEN LOOP RESETS THE STARTING JULIAN DAY TO
C   JAN. 1  00:00 AM  OF THE CURRENT YEAR
C
C CHANGE 2-DIGIT YEAR TO 4-DIGIT 
      IF (IYR.LT.1984) THEN
      IDYR=1984-IYR
      ILEAP=IDYR/4
      NDAY=IDYR*365+ILEAP
      JD=JD-NDAY
      ELSE IF (IYR.GT.1984) THEN
      IDYR=IYR-1984
      ILEAP=IDYR/4+1
      NDAY=IDYR*365+ILEAP
      JD=JD+NDAY
      END IF
C END CHANGE
C
      FJD = (FLOAT(IHR)+FLOAT(IMT)/60.)/24.0
C
      CALL SOLAR(JD,FJD,R,DLT,ALP,SLAG,1,HANG,TAUDA,COSZEN,SOLALT,
     1 ALATJZ)
      CALL ZENITH(FJD,DLT,SLAG,ALATJZ,HANG,DHR,COSZRS,FRAC,XLNG0,
     1  GMT)
      TAUDA = FRAC
      COSZEN= COSZRS
      RR2=R*R
      SWDTOP=(SC/RR2)*COSZEN*TAUDA

      IF (SWDTOP.EQ.0.0) THEN
      SWD=0.0
      SWR=SWD
      GO TO 73
      END IF
C****
C**** CALCULATE INSOLATION AT OCEAN SURFACE
C****
      FXA=1.0
C**** TRANSMISSION COEFF= 0.68 AFTER HSUING JGR'86
      TRANS=0.68
      TSEC=TRANS**(FXA/COSZEN)
C**** CALCULATE DIRECT SURFACE INSOLATION (ASSUME TRANS COEFF=.68)
      SWDSUR=TSEC*SWDTOP
C**** CALCULATE DIRECT+DIFFUSE (AFTER SMITHSONIAN APPROX.)
      ABSOR=0.91
      SWDSUR=SWDSUR+(ABSOR*SWDTOP-SWDSUR)*0.5
C****
C**** CALCULATE TOTAL SWD
C**** CALCULATE ALBEDO AFTER PAYNE JAS 72
      ZEN=RADIAN*ACOS(COSZEN)
      IF(ZEN.LT.74.0) GO TO 71
      JAB=INT(0.5*(90.0-ZEN)+1.0)
      GO TO 75
   71 IF(ZEN.LT.50.0) GO TO 72
      JAB=INT(0.23*(74.0-ZEN)+9.0)
      GO TO 75
   72 JAB=INT(0.1*(50.0-ZEN)+15.0)
   75 CONTINUE
      DZEN=-(ZEN-ZA(JAB))/DZA(JAB)
      ALBEDO=ALB1(JAB)+DZEN*(ALB1(JAB+1)-ALB1(JAB))
      SWDSUR=SWDSUR*(1.0-ALBEDO)
C**** TAKE CLOUDY CONDITIONS INTO ACCOUNT (AFTER REED JPO 77)
      SWD=SWDSUR*(1.0-P62*CLOUD+P19*SOLALT)
      SWR=SWD
   73 CONTINUE
C
C                  CALCULATE SATURATION MIXING RATIO
      ESTS=611.0*EXP(WRV*(RTREF-1.0/TSS))
      ESATS=ESTS
      QSAT=RD/RV*ESTS/(PSS-ESTS)
C**** CALC SAT VAPOR PRESS FOR DRY BULB TEMPERATURE DRYBT
      ESTA=611.0*EXP(WRV*(RTREF-1.0/DRYBT))
      ESATA= ESTA
      QASAT=RD/RV*ESTA/(PSS-ESTA)
C**** CALC MIXING RATIO FROM SAT VAPOR PRESS AND RH
      QKM=RH*QASAT
C                  CALCULATE VIRTUAL TEMPERATURE AND AIR DENSITY
      W1=1.0+QKM
      W2=RD/RV*W1
      W3=RD/RV+QKM
      W4=W3/W2
      VTEMP=DRYBT*W4
      W1=RD*VTEMP
      RHOAIR=PSS/W1
      RHOA=PSS/(RD*DRYBT*1.025E3)
C
C                  COMPUTE SENSIBLE HEAT FLUX
C
      W1 = RHOAIR * CPCH
      W2 = W1 * VMOD
      W3=TSS-DRYBT
      HNOT = W2 * W3
C
C                  COMPUTE LATENT HEAT FLUX
C
      W1 = RHOAIR * CEDW
      W2 = W1 * VMOD
      W3=QSAT-QKM
      ENOT = W2 * W3
      WENOT=W*ENOT
C
C	WENOT IS IN W/M2
C	PSS, QSAT AND QKM ARE IN PASCAL (N/M2), SEE P-276 OF BOUNDARY LAYER MET
C            WE USE HERE 611. NOT .611 IN ESTS FORMULA ABOVE THATS WHY IN PASCAL
C       1 MMHG = 1.33333 MBAR
C       SO TO GET F(W) IN W/M2 / (MMHG) AS FOLLOWS
C
	FWW = WENOT/W3/(PSS/0.622)  ! F(W) FUNCTION LAT HEAT = F(W)*(ESAT -EA)
	FWW = FWW*10**2*1.33333  ! N/M2 TO MB TO MMHG
	DIFEA = (ESTS-RH*ESTA)/1.0E2/1.3333  ! ESTS - ESTA; DIFF IN VAPOR PRESS
C
C     NET LONG WAVE (AFTER BERLIAND:SEE SIMPSON-PAULSON QJRMS 79)
C
      W1 = DRYBT**3 
      W2=W1*DRYBT
      W3=EMISS*SIGSB*W2*(P39-P05*SQRT(ESTA*1.0E-2))
      W4=EMISS*SIGSB*4.0*W1*(TSS-DRYBT)
C**** TAKE CLOUDINESS INTO ACCOUNT
      RLW =W3*(1.0-(P8*CLOUD))+W4
      AR=SWD
      SWD=SWD*(1.0-ATTEN(1))
C****
C**** COMPUTE TOTAL HEAT FLUX
C****
      HFS=SWD-RLW-HNOT-WENOT
!      PRINT*,"103",SWD,RLW,WENOT,HNOT,HFS,ALATJ,XLNG0,IYR,IMON,IDAY,IHR
!    + ,IMT,PSS,TSS,DRYBT,VMOD,RH,CLOUD,SWR,SC,RR2,COSZEN,TAUDA
C
C  CALCULATE PARTIAL DERIVATIVE DQ/DT:  (  DELTA(T)=3 DEG.)
C
      TSS=TSS+3.0
C
C                  CALCULATE SATURATION MIXING RATIO
      ESTS=611.0*EXP(WRV*(RTREF-1.0/TSS))
      QSAT=RD/RV*ESTS/(PSS-ESTS)
C
C                  COMPUTE SENSIBLE HEAT FLUX
C
      W1 = RHOAIR * CPCH
      W2 = W1 * VMOD
      W3=TSS-DRYBT
      HNOT1 = W2 * W3
C
C                  COMPUTE LATENT HEAT FLUX
C
      W1 = RHOAIR * CEDW
      W2 = W1 * VMOD
      W3=QSAT-QKM
      ENOT1 = W2 * W3
C
C     NET LONG WAVE (AFTER BERLIAND:SEE SIMPSON-PAULSON QJRMS 79)
C
      W1 = DRYBT**3
      W2=W1*DRYBT
      W3=EMISS*SIGSB*W2*(P39-P05*SQRT(ESTA*1.0E-2))
      W4=EMISS*SIGSB*4.0*W1*(TSS-DRYBT)
C**** TAKE CLOUDINESS INTO ACCOUNT
      RLW1 =W3*(1.0-(P8*CLOUD))+W4
      AR=SWD
      SWD=SWD*(1.0-ATTEN(1))
      HFS1=SWD-RLW1-HNOT1-W*ENOT1
      DHFS=(HFS1-HFS)/3.0
      DRYBT=DRYBT-273.16
      TSS=TSS-273.16-3.0

C     WRITE (6,80)
C     WRITE (6,90) IYR,IMON,IDAY,IHR,VMOD,ANGLE,
C    1 DRYBT,TSS,CLOUD,PSS,HFS,DHFS,SWR
   80 FORMAT(//5X,'INPUT AND OUTPUT INFORMATION'//
     1 ' YR ',' MON ',' DAY ',' HOUR','  VELOCITY  ',
     2 '  ANGLE(T)  ','  TEMPER.   ','    SST    ',
     3 '   CLOUD    ',' SURF PRESS.','   HEAT FLX ','  DQ/DT     ',
     4 '   SUN RAD. ')
   90 FORMAT(1X,I3,1X,I3,1X,I3,1X,I3,2X,1PE10.3,2X,E10.3,2X,
     1 E10.3,2X,E10.3,2X,E10.3,2X,E10.3,
     2 2X,E10.3,2X,E10.3,2X,E10.3)
C****
C**** INCLUDE DIVERGENCE OF DOWNWARD IRRADIANCE
C****
C     W3=AR*C2DTTS/60.0SO
C     DO 410 K=2,KB
C     TB(*,*,K)=TB(*,*,K)+(W3*ATTENZ(K))*FSM(*,*)
C 410 CONTINUE
C
C	*************************************************************
C
C	CALCULATES THE EQUILIBRIUM TEMP (TEMPE) AND TRANSFER COEFF.
C	(XKS), SETTING NET FLUX=0; AND TS=TE
C	FOR THEORITICAL COMPUTATIONS PLEASE SEE ONONDAGA LAKE FILE-2
C
C	*************************************************************
C
C	TRANSFER COEFFICIENT (XKS)
C
	DELTA=273.16
	W1=4.0*DELTA**3
	W2=W1*EMISS*SIGSB*(P39-P05*SQRT(ESTA*1.0E-2))   
	XKS1=W2*(1.0-P8*CLOUD)
C
	W1=16.0*DELTA**3*EMISS*SIGSB
	W2=12.0*EMISS*SIGSB*(DRYBTP+DELTA)*DELTA**2
	XKS2=W1-W2
C
	XKS3=RHOAIR*CPCH*VMOD
C
	XKS=-(XKS1+XKS2+XKS3)
C
C
C	CALCULATION OF EQUILIBRIUM TEMPERATURE (TEMPE)
C
	W1=-SWD
	W2=EMISS*SIGSB*DELTA**4
	W3=P39-P8*SQRT(ESTA*1.0E-2)
	W4=W3*(1.0-P8*CLOUD)
	W5=W2*W3*W4
	W6=-4.0*EMISS*SIGSB*DELTA**3*DRYBTP
	W7=-RHOAIR*CPCH*VMOD*DRYBTP
C
	TEMPE=(W1+W5+W6+W7)/XKS
C
	HEATXL=-XKS*(TEMPE-TSS)    ! LINEARIZED HEAT FLUX FROM XKS & TTS
C
      RETURN
      END SUBROUTINE HITFLX
      
      
      SUBROUTINE LONGWAVE(SST,TAIR,EA,C,RL1,RL2,RLW,RLWC)
CMNT  COMPUTE CLEAR SKY LONGWAVE, RLW, AFTER (CLARKE ET AL,
CMNT  1974) AND CLOUD CORRECTED LONGWAVE, RLWC.
CMNT  INPUT SST (DEG C), TAIR (DEG C), VAPOR PRESSURE (MB),
CMNT  AND CLOUD COVER (DECIMAL, 0 TO 1.0).  EMISSIVITY
CMNT  IS ASSUMED TO BE 0.98; SIGMA=STEFAN-BOLTZMANN CONST.
CMNT
CMNT  R.WELLER, 6/18/87
CMNT
       IMPLICIT NONE
	   REAL SST,TAIR,EA,C,RL1,RL2,RLW,RLWC,EPS,SIGMA,TKEL,SSTK
	   REAL TAIRK,TS4,TS3,DT,EASQR,B,CSQ,FC 

      EPS=0.98
      SIGMA=5.67E-08
      TKEL=273.16
      SSTK=SST+273.16
      TAIRK=TAIR+TKEL
      TS4=SSTK**4.
      TS3=SSTK**3.
      DT=SSTK-TAIRK
      EASQR=SQRT(EA)
      RL1=(EPS*SIGMA*TS4*(0.39-(0.05*EASQR)))
      RL2=4.*EPS*SIGMA*TS3*DT
      RLW=RL1+RL2
CMNT  COMPUTE CLOUD CORRECTION FACTOR (CLARKE ET AL 1974)
CMNT  B=0.62 HARDWIRED FOR 27 DEG NORTH
      B=0.62
      CSQ=C*C
      FC=1-(B*CSQ)
      RLWC=RLW*FC
      RETURN
      END  SUBROUTINE LONGWAVE
      
          
      SUBROUTINE SOLAR(JD,FJD,R,DLT,ALP,SLAG,N,HANG,TAUDA,COSZ,SOLALT,
     1 PHIT)
C*************************************************************************
C     ECOMSED MODEL
C     VERSION 1.3
C     FEBRUARY 2002
C*************************************************************************
*               COPYRIGHT (C) 2002, HYDROQUAL, INC.                      *
*                                                                        *
*  THESE CODED INSTRUCTIONS, STATEMENTS, AND COMPUTER PROGRAMS  CONTAIN  *
*  UNPUBLISHED  PROPRIETARY  INFORMATION OF HYDROQUAL, INC., AND         *
*  ARE PROTECTED BY FEDERAL COPYRIGHT LAW.  THEY  MAY  NOT BE DISCLOSED  *
*  TO  THIRD  PARTIES  OR COPIED OR DUPLICATED IN ANY FORM, IN WHOLE OR  *
*  IN PART, WITHOUT THE PRIOR WRITTEN CONSENT OF HYDROQUAL, INC.         *
*                                                                        *
* POINT OF CONTACT: ECOMSED-SUPPORT@HYDROQUAL.COM                        *
C*************************************************************************
C
C    *******************************************************************
C    *                                                                 *
C    *                            S O L A R                            *
C    *                                                                 *
C    *******************************************************************
C
C.....SOLAR COMPUTES RADIUS VECTOR, DECLINATION AND RIGHT ASCENSION OF
C.....SUN, EQUATION OF TIME, AND HOUR ANGLE OF SUN AT SUNSET FOR N
C.....EQUALLY SPACED LATITUDES GIVEN JULIAN DAY AND FRACTION.
C
        IMPLICIT NONE
        REAL, PARAMETER :: JMT=1
        REAL, PARAMETER :: TPI = 6.2831853
        REAL, PARAMETER :: HPI = 1.5707963
        REAL, PARAMETER :: RAD = 57.29578
        REAL, PARAMETER :: CYEAR = 365.25
        REAL, PARAMETER :: CCR = 1.E-6
        REAL, PARAMETER :: TPP = 1.55
        REAL, PARAMETER :: SVT6 = 78.035
        REAL, PARAMETER :: JDOR = 2415020
        REAL, PARAMETER :: ITERS = 100
        
        REAL,PARAMETER :: PI=ACOS(-1.0)
      
        REAL ALAT(JMT)
c		REAL TPI,HPI,RAD,CYEAR,CCR,TPP,SVT6,FJD,R,DLT,ALP,SLAG
		REAL FJD,R,DLT,ALP,SLAG
		REAL PHIT,PI,DAT,T,YEAR,TYEAR,EC,ANGIN,DELEQN,ADOR,JDOE
		REAL SNI,TINI,ER,QQ,E,EP,CD,HE,EQ,DATE,EM,CR,W,SIND,TST,SUN
		REAL PH,SS,CC,AP,EPS,H,AR,AC
c		INTEGER JDOR,ITERS,JD,N,ITER,I
		INTEGER JD,N,ITER,I
C
        REAL HANG, COSZ,  TAUDA, SOLALT
C
C.....TPP = DAYS BETWEEN EPOCH AND PERIHELION PASSAGE OF 1900
C.....SVT6 = DAYS BETWEEN PERIHELION PASSAGE AND MARCH EQUINOX OF 1900
C.....JDOR = JD OF EPOCH WHICH IS JANUARY 0, 1900 AT 12 HOURS UT
C
C
C    *******************************************************************
C
C


c      PI=ACOS(-1.0)
      ALAT(1)=PHIT
      DAT=FLOAT(JD-JDOR)-TPP+FJD

C
C    COMPUTES TIME IN JULIAN CENTURIES AFTER EPOCH
C
      T=FLOAT(JD-JDOR)/36525.0
C
C    COMPUTES LENGTH OF ANOMALISTIC AND TROPICAL YEARS (MINUS 365 DAYS)
C
      YEAR=0.25964134+0.304E-5*T
      TYEAR=0.24219879-0.614E-5*T
C
C    COMPUTES ORBIT ECCENTRICITY AND ANGLE OF EARTH'S INCLINATION FROM T
C
      EC=0.01675104-(0.418E-4+0.126E-6*T)*T
      ANGIN=23.452294-(0.0130125+0.164E-5*T)*T
      ADOR=FLOAT(JDOR)
      JDOE=ADOR+(SVT6*CYEAR)/(YEAR-TYEAR)
C
C    DELEQN=UPDATED SVT6 FOR CURRENT DATE
C
C
C
      DELEQN=(JDOE-FLOAT(JD))*(YEAR-TYEAR)/CYEAR
C
      YEAR=YEAR+365.0
C
      SNI=SIN(ANGIN/RAD)
      TINI=1.0/TAN(ANGIN/RAD)
      ER=SQRT((1.0+EC)/(1.0-EC))
      QQ=DELEQN*TPI/YEAR
C
C    DETERMINE TRUE ANOMALY AT EQUINOX
C
      E=1.0
C
      DO 200 ITER=1,ITERS
      EP=E-(E-EC*SIN(E)-QQ)/(1.0-EC*COS(E))
      CD=ABS(E-EP)
      E=EP
      IF(CD.LE.CCR) GO TO 250
 200  CONTINUE
      PRINT 400
 250  CONTINUE
      HE=0.5*E
      EQ=2.0*ATAN(ER*TAN(HE))
C
C    DATE=DAYS SINCE LAST PERIHELION PASSAGE
C
      DATE=MOD(DAT,YEAR)
C
C    SOLVE ORBIT EQUATIONS BY NEWTON'S METHOD
C
      EM=TPI*DATE/YEAR
      E=1.0

C
      DO 300 ITER=1,ITERS
      EP=E-(E-EC*SIN(E)-EM)/(1.0-EC*COS(E))
      CR=ABS(E-EP)
      E=EP
      IF(CR.LE.CCR) GO TO 350
 300  CONTINUE
      PRINT 400
 350  CONTINUE
C
      R=1.0-EC*COS(E)
      HE=0.5*E
      W=2.0*ATAN(ER*TAN(HE))
      SIND=SNI*SIN(W-EQ)
      DLT=ASIN(SIND)
      ALP=ASIN(TAN(DLT)*TINI)
      TST=COS(W-EQ)
C
      IF(TST.LT.0.0) ALP=PI-ALP
C
      IF(ALP.LT.0.0) ALP=ALP+TPI
C
      SUN=TPI*(DATE-DELEQN)/YEAR
      IF (SUN.LT.0.0)  SUN=SUN+TPI
      SLAG=SUN-ALP-0.03255
C    COMPUTE HOUR ANGLE OF SUNSET AT ALL LATITUDES
C
C
      DO 1 I=1,N
      PH=ALAT(I)
      SS=SIN(PH)*SIN(DLT)
      CC=COS(PH)*COS(DLT)
C
!     SOLALT(I)= SS + CC
      SOLALT= MAX(MIN((SS + CC),1.),-1.)
      SOLALT = ASIN(SOLALT) * RAD
C
      IF(DLT.EQ.0.0) GO TO 16
C
      AP=ABS(PH)
      EPS=ABS(AP-HPI)
      IF(EPS.GT.CCR) GO TO 14
C
      H=HPI*ABS(AP/PH+ABS(DLT)/DLT)
      GO TO 5
C
14    AR=-SS/CC
      AC=ABS(AR)
      IF(AC-1.0+CCR) 4,2,3
C
2     H=(AC-AR)*HPI
C
      GO TO 5
C
3     IF(AR.LT.0.0) GO TO 25
C
      H=0.0
      GO TO 5
C
25    H=PI
      GO TO 5
C
C
16    H=HPI
      GO TO 5
C
4     H=ACOS(AR)
5     HANG=H
      TAUDA=MAX(H/PI,0.0)
C
      IF(H.EQ.0.0) GO TO 100
C
!	WRITE(*,*)'H IN SOLAR=',H
      COSZ=MAX((SS+CC*SIN(H)/H),0.0)
      GO TO 1
C
C
C
100   COSZ=0.0
1     CONTINUE
C
      RETURN
400   FORMAT('0 MAXIMUM ITERATIONS IN SUBROUTINE SOLAR')
      END SUBROUTINE SOLAR
      

      SUBROUTINE VAPOR(EA,ES,RH,SST,BP)
		  IMPLICIT NONE
C
CMNT  RH IN PERCENT, SST IN DEG C, BP IN MB
CMNT  COMPUTE VAPOR PRESSURE OF WATER FROM RELATIVE
CMNT  HUMIDITY
CMNT
CMNT  R.WELLER, 6/18/87
CMNT
CMNT  COMPUTE SATURATION VAPOR PRESSURE OF PURE WATER
CMNT  USING TABATA FORMULA
C**********************************************************
C	MODIFIED NOVEMBER 6, 1990	M. PARK SAMELSON
C	
C	PREVIOUSLY USED TABATA FORMULA (1973).  THIS
C	VERSION USES BUCK FORMULA (1981).  TEMPERATURE
C	IS IN DEGREES C INSTEAD OF DEGREES K.
C
C**********************************************************

C*******TABATA FORMULA**************
C**** TK=273.16
C**** SSTK=SST+TK
C**** A=1000./SSTK
C**** E=8.42926609-(1.82717483*A)-(.071208271*A*A)
C**** ES=10.**E

C********BUCK FORMULA***************
       REAL EA,ES,RH,SST,BP,EW,B,RW,R
	   
	   
      ES = (1.0007+3.46E-6*BP)*6.1121*EXP(17.502 * SST/ (240.97 + SST))

CMNT  CORRECT FOR SALT WATER AT 35 PPT
      EW=.9815*ES
CMNT  COMPUTE SATURATION MIXING RATIO
      B=EW/BP
      RW=(B*.62197)/(1.-B)
CMNT  COMPUTE MIXING RATIO
      R=(RH/100.)*RW
CMNT  COMPUTE VAPOR PRESSURE
      EA=(R/(.62197+R))*BP
      RETURN
      END SUBROUTINE VAPOR
      
      
      SUBROUTINE ZENITH(FJD,DLT,SLAG,XLAT,HA,DHR,COSZ,FRAC,XLNG0,
     1  GMT)
	 IMPLICIT NONE
C*************************************************************************
C     ECOMSED MODEL
C     VERSION 1.3
C     FEBRUARY 2002
C*************************************************************************
*               COPYRIGHT (C) 2002, HYDROQUAL, INC.                      *
*                                                                        *
*  THESE CODED INSTRUCTIONS, STATEMENTS, AND COMPUTER PROGRAMS  CONTAIN  *
*  UNPUBLISHED  PROPRIETARY  INFORMATION OF HYDROQUAL, INC., AND         *
*  ARE PROTECTED BY FEDERAL COPYRIGHT LAW.  THEY  MAY  NOT BE DISCLOSED  *
*  TO  THIRD  PARTIES  OR COPIED OR DUPLICATED IN ANY FORM, IN WHOLE OR  *
*  IN PART, WITHOUT THE PRIOR WRITTEN CONSENT OF HYDROQUAL, INC.         *
*                                                                        *
* POINT OF CONTACT: ECOMSED-SUPPORT@HYDROQUAL.COM                        *
C*************************************************************************
C
C    *******************************************************************
C    *                                                                 *
C    *                           Z E N I T H                           *
C    *                                                                 *
C    *******************************************************************
C

      REAL,PARAMETER :: PI=ACOS(-1.0)
      REAL,PARAMETER :: TPI=2.0*PI
      REAL,PARAMETER :: CVPR=TPI
      REAL,PARAMETER :: PID24 = .13089969
       
       REAL FJD,DLT,SLAG,XLAT,HA,DHR,COSZ,FRAC,XLNG0,GMT,PI !,PID24,TPI,CVPR
	  REAL FJDL,GHA,ARG,SINFRAC,SS,CC,CONS,XLNG,HLOC,HLPAR,ARMHL,DELSH
c	  REAL DELE,CVPR,SINFAC,DELW
	  REAL DELE,SINFAC,DELW

      LOGICAL RISE,  SET
C
C    *******************************************************************
C
C     ZENITH COMPUTES EFFECTIVE MEAN COSINE OF ZENITH ANGLE AND DAYLIGHT
C       FRACTION FROM LATITUDE AND PARAMETERS GIVEN BY SUBROUTINE SOLAR
C
C     INPUT ARGUMENTS TO CIRCULAR FUNCTIONS ARE IN RADIANS
C
c      PI=ACOS(-1.0)
c      TPI=2.0*PI
c      CVPR=TPI
C
C  SHIFT TIME BY GMT HOURS TO PUT IT IN GMT
C
      FJDL=FJD-GMT/24.0
C
      IF (FJDL.LT.0.0) FJDL=FJDL+1.0
      GHA=FJDL*TPI+SLAG
      ARG=DHR*PID24
      SINFAC=SIN(ARG)/ARG
      SS=SIN(XLAT)*SIN(DLT)
      CC=COS(XLAT)*COS(DLT)
      IF(HA.GT.0.0) CONS=SS+CC*SIN(HA)/HA
C
C   SET LONGITUDE IN RADIAN
C
      XLNG=(XLNG0+180.0)*PI/180.0
      HLOC=GHA+ARG+XLNG
C     LOCAL HOUR ANGLE SHIFTED BY HALF OF THE AVERAGING PERIOD
      RISE=.FALSE.
      SET=.FALSE.
      HLOC=MOD(HLOC,TPI)
      IF(HLOC.GT.PI) HLOC=HLOC-TPI
      HLPAR=HLOC+ARG
      ARMHL=ARG-HLOC
      IF(HLPAR.GT.HA) SET=.TRUE.
      IF(ARMHL.GT.HA) RISE=.TRUE.
      IF(RISE.AND.SET) GO TO 7
      IF(HLPAR.GT.PI) GO TO 8
      IF(ARMHL.GT.PI) GO TO 9
      IF(SET) GO TO 3
      IF(RISE) GO TO 4
      FRAC=1.0
      COSZ=SS+CC*COS(HLOC)*SINFAC
      GO TO 2
3     DELSH=0.5*(HA+ARMHL)
      GO TO 5
4     DELSH=0.5*(HA+HLPAR)
5     IF(DELSH.LE.0.0) GO TO 6
      FRAC=DELSH/ARG
C	WRITE(*,*)'DELSH=',DELSH
      COSZ=SS+CC*COS(HA-DELSH)*SIN(DELSH)/DELSH
      GO TO 2
7     IF(HA.LE.0.0) GO TO 6
      FRAC=HA/ARG
      COSZ=CONS
      GO TO 2
8     DELE=0.5*MAX(HLPAR+HA-TPI,0.0)
      DELW=0.5*MAX(HA+ARMHL,0.0)
      GO TO 10
9     DELE=0.5*MAX(HA+HLPAR,0.0)
      DELW=0.5*MAX(ARMHL+HA-TPI,0.0)
10    FRAC=(DELE+DELW)/ARG
      IF(FRAC.EQ.0.0) GO TO 11
      COSZ=SS+CC*(COS(HA-DELE)*SIN(DELE)+
     1               COS(HA-DELW)*SIN(DELW))/(DELE+DELW)
      GO TO 2
6     FRAC=0.0
11    COSZ=0.0
2     CONTINUE
      COSZ = MIN(1.0,COSZ)
      COSZ = MAX(0.0,COSZ)
      FRAC = MIN(1.0,FRAC)
      RETURN
      END SUBROUTINE ZENITH
      
      
       REAL FUNCTION QSAT0(T,P)
	   IMPLICIT NONE
C*************************************************************************
C     ECOMSED MODEL
C     VERSION 1.3
C     FEBRUARY 2002
C*************************************************************************
*               COPYRIGHT (C) 2002, HYDROQUAL, INC.                      *
*                                                                        *
*  THESE CODED INSTRUCTIONS, STATEMENTS, AND COMPUTER PROGRAMS  CONTAIN  *
*  UNPUBLISHED  PROPRIETARY  INFORMATION OF HYDROQUAL, INC., AND         *
*  ARE PROTECTED BY FEDERAL COPYRIGHT LAW.  THEY  MAY  NOT BE DISCLOSED  *
*  TO  THIRD  PARTIES  OR COPIED OR DUPLICATED IN ANY FORM, IN WHOLE OR  *
*  IN PART, WITHOUT THE PRIOR WRITTEN CONSENT OF HYDROQUAL, INC.         *
*                                                                        *
* POINT OF CONTACT: ECOMSED-SUPPORT@HYDROQUAL.COM                        *
C*************************************************************************
C
C	T 	TEMPERATURE IN DEGREES C
C	P 	PRESSURE IN MILLIBARS
C	ES	SATURATION VAPOR PRESSURE IN MILLIBARS
C	QSAT	SATURATION HUMIDITY IN G/KG 
C
       REAL RD,RV,EPS,ES,T,P
      RD = 287.05
      RV = 461.5

      EPS = RD/RV

C*********SATURATION VAPOR PRESSURE**********
      ES = (1.0007+3.46E-6*P) * 6.1121 * EXP(17.502 * T/ (240.97 + T))

C*********CONVERT TO SATURATION HUMIDITY*****
      QSAT0 = 1000. * EPS * ES / ( P + ES * (EPS - 1.0))

      RETURN
      END FUNCTION QSAT0
#endif

      
      
      END MODULE MOD_HEAT