      SUBROUTINE NMC_DIFF

      USE MOD_GLOBAL
c      USE IFPORT
      
      IMPLICIT NONE
      
      INTEGER,PARAMETER::IMNMC=337,JMNMC=225,KBM1NMC=10,KBNMC=11
      
	REAL S1NMC(N_CTRDP1,KBNMC),S2NMC(N_CTRDP1,KBNMC)
      REAL XONMC(100),YONMC(100),DIS11NMC(100)
      REAL ERONMC(100,9999,KBM1NMC)
      REAL DIS000ONMC(100,9999)
      INTEGER IINMC(100,9999)
      REAL, ALLOCATABLE :: DIFFNMC(:,:)
      REAL THOURNMC,XXNMC,SRNMC,LENGTHNMC
      REAL RADIUSNMC,DISNMC,MEANDISNMC,DISMINNMC
      REAL DMMF,DIIF,KKKNMC,KKK1NMC
      INTEGER INMC,JNMC,RELNMC,I,K
      INTEGER KNMC,KKNMC,NNNMC,NNNNMC,MMNMC,MMMNMC,CCNMC,BBNMC,IND
      CHARACTER*80 FN1NMC,FN2NMC,FN4NMC
      CHARACTER*80 F2NMC
      
      REAL  XBOUND(4)
      REAL  YBOUND(4)
      
      KKKNMC=-0.8611
      KKK1NMC=1.1614
      DIS11NMC=0
      
c      RELNMC=MAKEDIRQQ(TRIM('output/NMC'))
c      RELNMC=MAKEDIRQQ(TRIM('output/NMC/DIFF'))
c      RELNMC=MAKEDIRQQ(TRIM('output/NMC/B'))
      CALL SYSTEM("mkdir output/NMC")
      CALL SYSTEM("mkdir output/NMC/DIFF")
      CALL SYSTEM("mkdir output/NMC/B")
      
      FN1NMC='input/TEST_S_FIELD_A.DAT'
      FN2NMC='input/TEST_S_FIELD_B.DAT'
	OPEN(10,FILE=FN1NMC)
      OPEN(20,FILE=FN2NMC)
      DO I=1,N_CTRDP1
	    READ(10,*) (S1NMC(I,K),K=1,11)
	    READ(20,*) (S2NMC(I,K),K=1,11)
      ENDDO
      OPEN(40,FILE='input/OBSERVEDDATA.DAT')
      OPEN(50,FILE='output/NMC/NN1.DAT')
      OPEN(55,FILE='output/NMC/N.DAT')
      OPEN(66,FILE='output/NMC/H.DAT')
      OPEN(65,FILE='output/NMC/DIS.DAT')
      
	IINMC=0
      
      
	NNNMC=1
c      DO WHILE(.NOT.EOF(40))
      DO WHILE(1)
	    READ(40,*,end=201) XONMC(NNNMC),YONMC(NNNMC)
          NNNMC=NNNMC+1
      ENDDO
201   continue
      REWIND(40)
      
      CCNMC=NNNMC
      NNNMC=1
c	DO WHILE(.NOT.EOF(40))
      DO WHILE(1)
      READ(40,*,end=202) XONMC(NNNMC),YONMC(NNNMC)      
      DISNMC=4000.  !影响半径
      MMNMC=0
      MEANDISNMC=0.
      DO INMC=1,N_CTRD
          RADIUSNMC=SQRT((XONMC(NNNMC)-XR(INMC))**2+(YONMC(NNNMC)
     *    -YR(INMC))**2)
          IF(RADIUSNMC.LE.DISNMC.AND.FSM(INMC).GE.0.)THEN
              MMNMC=MMNMC+1
              IINMC(NNNMC,MMNMC)=INMC
              DIS000ONMC(NNNMC,MMNMC)=RADIUSNMC
              MEANDISNMC=MEANDISNMC+1./DIS000ONMC(NNNMC,MMNMC)**2.
          ENDIF
      ENDDO
      MMNMC=MMNMC-1
      WRITE(50,'(I10)')MMNMC   
      DO MMMNMC=1,MMNMC
          WRITE(50,'(I10)') IINMC(NNNMC,MMMNMC)
      ENDDO
      WRITE(55,'(I10)') MMNMC
      WRITE(66,'(I10)') NNNMC     
      DO MMMNMC=1,MMNMC
          WRITE(66,*)1./DIS000ONMC(NNNMC,MMMNMC)**2./MEANDISNMC 
      ENDDO    
      WRITE(65,'(I10)')NNNMC    
      DO MMMNMC=1,MMNMC
          WRITE(65,'(G20.8)')DIS000ONMC(NNNMC,MMMNMC)
      ENDDO    
      NNNMC=NNNMC+1
      ENDDO    
202   continue
      CLOSE(40)
      CLOSE(50)
      CLOSE(55)
      CLOSE(60)
      CLOSE(65)
      DO NNNNMC=1,NNNMC-1
	    WRITE(F2NMC,1000)NNNNMC
	    FN4NMC='output/NMC/DIFF/'//TRIM(F2NMC)//'.DAT'
	    OPEN(888,FILE=FN4NMC,FORM='UNFORMATTED',CONVERT='BIG_ENDIAN')
          DO KNMC=1,KBM1NMC
	    DO MMNMC=1,99999
              
          IF (IINMC(NNNNMC,MMNMC).NE.0)THEN
              ERONMC(NNNNMC,MMNMC,KNMC)=S1NMC(IINMC(NNNNMC,MMNMC),KNMC)-
     *        S2NMC(IINMC(NNNNMC,MMNMC),KNMC)
          ELSE
	            GOTO 111
          ENDIF
	    ENDDO
111       ENDDO
          MMNMC=MMNMC-2 !!! 前面减了1，这里就要减2
	    ALLOCATE (DIFFNMC(MMNMC,MMNMC))
          DO KNMC=1,KBM1NMC
              
          DMMF=99999.
          DIIF=0.
          DO INMC=1,MMNMC
          DO JNMC=1,MMNMC
              DIFFNMC(INMC,JNMC)=ERONMC(NNNNMC,INMC,KNMC)*
     *        ERONMC(NNNNMC,JNMC,KNMC)
              IF(DIFFNMC(INMC,JNMC).LE.0)THEN
                  DIFFNMC(INMC,JNMC)=0.5
              ELSE IF(DIFFNMC(INMC,JNMC).GT.0.0.AND.
     *DIFFNMC(INMC,JNMC).LT.0.2)THEN
                  DIFFNMC(INMC,JNMC)=1.
              ELSE
                  DIFFNMC(INMC,JNMC)=1.5
              ENDIF
	            DIIF=MAX(DIIF,DIFFNMC(INMC,JNMC))
	            DMMF=MIN(DMMF,DIFFNMC(INMC,JNMC))
          ENDDO
          ENDDO
          WRITE(888)DIFFNMC
	    ENDDO
          DEALLOCATE (DIFFNMC)
          CLOSE(888)
      ENDDO

1000  FORMAT (I6.6)
      
      CALL INTER_S_VERTICAL
      CALL NO_INVERSION
      END SUBROUTINE NMC_DIFF