c!$OMP TARGET UPDATE FROM(D,EL,DUM,DVM,FSM,WUBOT,WVBOT) !GPU to CPU fo WRITE_RST.h
c!$OMP TARGET UPDATE FROM(KM,KH,KQ,Q2,Q2L,L,U,V,W,T,S) !GPU to CPU fo WRITE_RST.h
c!$OMP TARGET UPDATE FROM(ELF,UF,VF,TPS,AAUU,AAVV,BBBB,AAZZ) !GPU to CPU fo WRITE_RST.h
c!$OMP TARGET UPDATE FROM(XFLUX,YFLUX,XMFLUX,YMFLUX,AAM,DU,DV) !GPU to CPU fo WRITE_RST.h

		OPEN (IUWRS, FORM='UNFORMATTED', FILE=FN)
		WRITE (IUWRS) TDAY,TG
          WRITE (IUWRS) NSTEP, DZR, Z, ZZ, DZ, DZZ, H, H1, H2, H3, DJ
     * , D, EL, ARU, ARV,DUM, DVM, FSM, COR, WUBOT, WVBOT
     * , KM, KH, KQ, Q2, Q2L, L, U,V,W, T, S, RHO
     * , FSMADD, ELF  
          WRITE (IUWRS) UF,VF,HU,HV,TPS,AAUU,AAVV,BBBB,AAZZ
          WRITE (IUWRS) XFLUX,YFLUX,XMFLUX,YMFLUX,AAM,DU,DV
          WRITE (IUWRS) XXI,XETA,YXI,YETA
          WRITE (IUWRS) CBC_COF,KM_COF,KH_COF
  
          !SED
#ifdef MODULE_SED
*          IF (LOG_SED) THEN
          WRITE (IUWRS)  SED,D50,TAU,TAUE,TAUD,TAUE0,TAUD0,
     * QDEP,QERO,ZBED,ZBEDD,SUMH !LXY
#endif
#ifdef MODULE_WAVE
        WRITE(IUWRS) HSIG, TSIG, WAVEDIR
#endif   
#ifdef MODULE_MAT
       WRITE(IUWRS) CONCENTRATION
#endif   
*          ENDIF
  
          CLOSE (IUWRS) 